# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olap', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DimDate',
        ),
        migrations.RemoveField(
            model_name='dimsession',
            name='date_dayinweek',
        ),
        migrations.RemoveField(
            model_name='dimsession',
            name='date_id',
        ),
        migrations.RemoveField(
            model_name='dimsession',
            name='date_week',
        ),
        migrations.RemoveField(
            model_name='dimsession',
            name='date_year',
        ),
        migrations.RemoveField(
            model_name='dimsession',
            name='unixtimestamp',
        ),
        migrations.RemoveField(
            model_name='dimsubmissionattempt',
            name='unixtimestamp',
        ),
        migrations.RemoveField(
            model_name='dimsubmissiontype',
            name='timeclose',
        ),
        migrations.RemoveField(
            model_name='dimsubmissiontype',
            name='timeopen',
        ),
        migrations.RemoveField(
            model_name='factcoursevisit',
            name='date_id',
        ),
        migrations.RemoveField(
            model_name='factcoursevisit',
            name='time_id',
        ),
        migrations.RemoveField(
            model_name='factcoursevisit',
            name='unixtimestamp',
        ),
        migrations.RemoveField(
            model_name='summarypost',
            name='date_id',
        ),
        migrations.AddField(
            model_name='dimsession',
            name='first_visit',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimsubmissionattempt',
            name='attempted_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factcoursevisit',
            name='visited_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summarypost',
            name='posted_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
