# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_owner_to_owners'),
        ('olap', '0002_remove_dimdate_and_fix_times'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dimpage',
            unique_together=set([('course', 'content_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='dimuser',
            unique_together=set([('course', 'lms_id')]),
        ),
    ]
