# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olap', '0003_DimPage_unique_together_course_content_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimsession',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='dimsubmissionattempt',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='factcoursevisit',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='summarypost',
            name='user_id',
        ),
        migrations.AddField(
            model_name='dimsubmissionattempt',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='olap.DimUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factcoursevisit',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='olap.DimUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summarypost',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='olap.DimUser'),
            preserve_default=False,
        ),
    ]
