# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olap', '0005_replace_many_integer_fk_references_with_proper_foreign_keys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimpage',
            old_name='course',
            new_name='course_offering',
        ),
        migrations.RenameField(
            model_name='dimsession',
            old_name='course',
            new_name='course_offering',
        ),
        migrations.RenameField(
            model_name='dimsubmissiontype',
            old_name='course',
            new_name='course_offering',
        ),
        migrations.RenameField(
            model_name='dimuser',
            old_name='course',
            new_name='course_offering',
        ),
        migrations.RenameField(
            model_name='summarycourseassessmentvisitsbydayinweek',
            old_name='course',
            new_name='course_offering',
        ),
        migrations.RenameField(
            model_name='summarycoursecommunicationvisitsbydayinweek',
            old_name='course',
            new_name='course_offering',
        ),
        migrations.RenameField(
            model_name='summarycoursevisitsbydayinweek',
            old_name='course',
            new_name='course_offering',
        ),
        migrations.RenameField(
            model_name='summarydiscussion',
            old_name='course',
            new_name='course_offering',
        ),
        migrations.RenameField(
            model_name='summaryforum',
            old_name='course',
            new_name='course_offering',
        ),
        migrations.RenameField(
            model_name='summaryparticipatingusersbydayinweek',
            old_name='course',
            new_name='course_offering',
        ),
        migrations.RenameField(
            model_name='summarypost',
            old_name='course',
            new_name='course_offering',
        ),
        migrations.RenameField(
            model_name='summarysessionaveragelengthbydayinweek',
            old_name='course',
            new_name='course_offering',
        ),
        migrations.RenameField(
            model_name='summarysessionaveragepagespersessionbydayinweek',
            old_name='course',
            new_name='course_offering',
        ),
        migrations.RenameField(
            model_name='summarysessionsbydayinweek',
            old_name='course',
            new_name='course_offering',
        ),
        migrations.RenameField(
            model_name='summaryuniquepageviewsbydayinweek',
            old_name='course',
            new_name='course_offering',
        ),
        migrations.RemoveField(
            model_name='dimsubmissionattempt',
            name='course',
        ),
        migrations.AlterUniqueTogether(
            name='dimpage',
            unique_together=set([('course_offering', 'content_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='dimuser',
            unique_together=set([('course_offering', 'lms_id')]),
        ),
    ]
