# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_course_to_course_offering'),
        ('olap', '0006_rename_course_to_course_offering'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DimUser',
            new_name='LMSUser',
        ),
        migrations.RenameField(
            model_name='dimsubmissionattempt',
            old_name='user',
            new_name='lms_user',
        ),
        migrations.RenameField(
            model_name='factcoursevisit',
            old_name='user',
            new_name='lms_user',
        ),
        migrations.RenameField(
            model_name='lmsuser',
            old_name='lms_id',
            new_name='lms_user_id',
        ),
        migrations.RenameField(
            model_name='summarypost',
            old_name='user',
            new_name='lms_user',
        ),
        migrations.AlterUniqueTogether(
            name='lmsuser',
            unique_together=set([('course_offering', 'lms_user_id')]),
        ),
    ]
