# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olap', '0007_rename_DimUser_to_User'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FactCourseVisit',
            new_name='PageVisit',
        ),
    ]
