# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olap', '0008_rename_FactCourseVisit_to_PageVisit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DimPage',
            new_name='Page',
        ),
    ]
