# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olap', '0009_rename_DimPage_to_Page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DimSession',
            new_name='LMSSession',
        ),
    ]
