# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olap', '0010_rename_DimSession_to_LMSSession'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DimSubmissionAttempt',
            new_name='SubmissionAttempt',
        ),
    ]
