# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olap', '0012_rename_DimSubmissionType_to_SubmissionType'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarypost',
            name='course_offering',
        ),
        migrations.RemoveField(
            model_name='summarypost',
            name='discussion_id',
        ),
        migrations.RenameField(
            model_name='summarypost',
            old_name='forum_id',
            new_name='page_id',
        ),
    ]
