# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olap', '0013_page_parent_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionattempt',
            name='attempt_key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
