# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olap', '0014_submissionattempt_attempt_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='lms_activity_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
