# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olap', '0014_change_page_id_to_page_for_posts'),
        ('olap', '0015_pagevisit_lms_activity_id'),
    ]

    operations = [
    ]
