# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olap', '0019_change_SubmissionAttempt_grade_to_Decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionattempt',
            name='grade',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
