# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_owner_to_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserepeatingevent',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
    ]
