# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_owner_to_owners'),
        ('olap', '0005_replace_many_integer_fk_references_with_proper_foreign_keys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='CourseOffering',
        ),
        migrations.RenameField(
            model_name='courserepeatingevent',
            old_name='course',
            new_name='course_offering',
        ),
        migrations.RenameField(
            model_name='coursesingleevent',
            old_name='course',
            new_name='course_offering',
        ),
        migrations.RenameField(
            model_name='coursesubmissionevent',
            old_name='course',
            new_name='course_offering',
        ),
        migrations.RenameField(
            model_name='pedagogyhelper',
            old_name='course',
            new_name='course_offering',
        ),
    ]
