# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 05:54
from __future__ import unicode_literals

from datetime import datetime
import pytz

from django.conf import settings
from django.db import migrations
from django.db import models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_require_values_for_submission_event_start_and_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
