# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_courseoffering_last_activity_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='is_importing',
            field=models.BooleanField(default=False),
        ),
    ]
