# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_courseoffering_is_importing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
