# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('dashboard', '0009_unique_course_offering_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descriptions', models.TextField(blank=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authtoken.Token')),
            ],
        ),
    ]
