# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_lmsserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='lms_server',
            field=models.ForeignKey(blank=True, help_text='If empty, then this course offering will not be able to be imported', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.LMSServer'),
        ),
    ]
