# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-15 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_course_uniqueness_to_include_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='start_date',
            field=models.DateField(help_text='Start date must be on a Monday'),
        ),
    ]
