const {
    BASE_URL,
    BASE_API_URL,
    PAGE_TYPE_CONTENT,
    PAGE_TYPE_COMMUNICATION,
    PAGE_TYPE_ASSESSMENT,
} = window.__APP_CONTEXT__; // eslint-disable-line

export {
    BASE_API_URL,
    BASE_URL,
    PAGE_TYPE_CONTENT,
    PAGE_TYPE_COMMUNICATION,
    PAGE_TYPE_ASSESSMENT,
};
